### ISSUE TITLE
Spelling mistakes

### ISSUE THREAD

**Issue by dpnkrpl** [wow-actions/auto-comment#3]
Hi @bubkoo , this action works like a pro 😎. I'm really impressed with it. It would be great if you correct some serious spelling mistakes in comment messages.

**Comment by dpnkrpl** [comment]
Change
 `thank your` to `thank you`
`a issue` to `an issue`
`will try` to `will investigate into the matter`

**Comment by bubkoo** [comment]
@deep5050 fixed in https://github.com/bubkoo/auto-comment/releases/tag/v1.0.4
